name: Deploy to External GitHub Pages

on:
  push:
    branches: [pages]
  pull_request:
    branches: [pages]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      permissions:
        pages: write
        id-token: write

      steps:
        - name: Deploy para GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
